/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;
/**
 *
 * @author Dani
 */
public class ERPMain extends javax.swing.JFrame {

    /**
     * Creates new form ERPMain
     */
    
    public static MySQL db = new MySQL();
    public static MetGlob mt = new MetGlob();
    public ERPMain() {
        initComponents();
        initCustomComponents();
        db.MySQLConnection("localhost","3306","empresa","root","");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void initCustomComponents(){
        JPProductos jp = new JPProductos();
        jTabbedPane.addTab("Productos", jp);

        JPProveedores jprov = new JPProveedores();
        jTabbedPane.addTab("Proveedores", jprov);
        
        JPPedidos jpedi = new JPPedidos();
        jTabbedPane.addTab("Pedidos", jpedi);
        
       
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        jPClientes = new javax.swing.JPanel();
        jLClientes = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBMostrarClientes = new javax.swing.JButton();
        jTFBuscarC = new javax.swing.JTextField();
        jBBuscarC = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTFIDC = new javax.swing.JTextField();
        jTFNombreC = new javax.swing.JTextField();
        jTFApellido1 = new javax.swing.JTextField();
        jTFApellido2 = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jTFDireccion = new javax.swing.JTextField();
        jTFCiudad = new javax.swing.JTextField();
        jBAnadirC = new javax.swing.JButton();
        jBActualizarC = new javax.swing.JButton();
        jBModificarC = new javax.swing.JButton();
        jBEliminarC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane.setBackground(new java.awt.Color(51, 153, 255));
        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);

        jLClientes.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLClientes.setText("CLIENTES");

        jTable.setAutoCreateRowSorter(true);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable);

        jLabel1.setText("Buscar por:");

        jBMostrarClientes.setText("Mostrar todos");
        jBMostrarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarClientesActionPerformed(evt);
            }
        });

        jBBuscarC.setText("Buscar");
        jBBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarCActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("ID");

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido1");

        jLabel5.setText("Apellido2");

        jLabel6.setText("Telefono");

        jLabel7.setText("Direccion");

        jLabel8.setText("Ciudad");

        jBAnadirC.setText("Añadir");
        jBAnadirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnadirCActionPerformed(evt);
            }
        });

        jBActualizarC.setText("Actualizar");
        jBActualizarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFApellido2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTFNombreC)
                            .addComponent(jTFApellido1)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFIDC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(96, 96, 96)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFTelefono)
                    .addComponent(jTFDireccion)
                    .addComponent(jTFCiudad, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBActualizarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAnadirC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jTFIDC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAnadirC))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addComponent(jTFNombreC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTFDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBActualizarC))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jTFCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jTFApellido1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTFApellido2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jBModificarC.setText("Modificar");
        jBModificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarCActionPerformed(evt);
            }
        });

        jBEliminarC.setText("Eliminar");
        jBEliminarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPClientesLayout = new javax.swing.GroupLayout(jPClientes);
        jPClientes.setLayout(jPClientesLayout);
        jPClientesLayout.setHorizontalGroup(
            jPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLClientes)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(jPClientesLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscarC)
                        .addGap(18, 18, 18)
                        .addComponent(jBMostrarClientes))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBModificarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEliminarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPClientesLayout.setVerticalGroup(
            jPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLClientes)
                .addGap(18, 18, 18)
                .addGroup(jPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMostrarClientes)
                    .addComponent(jTFBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPClientesLayout.createSequentialGroup()
                        .addComponent(jBModificarC)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminarC)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Clientes", jPClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBEliminarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarCActionPerformed
        int fila = jTable.getSelectedRow();
        if(fila>=0){
            int res=JOptionPane.showConfirmDialog(rootPane, "¿Desea borrar el usuario seleccionado?", "Eliminar", JOptionPane.OK_CANCEL_OPTION);
            if(res==0){
                String Query ="DELETE FROM clientes WHERE clienteID = \""+jTable.getValueAt(fila, 0).toString()+"\"";
                db.deleteRecord(Query);
            }
        }
        else{JOptionPane.showMessageDialog(null, "Seleccione una fila.");}
    }//GEN-LAST:event_jBEliminarCActionPerformed

    private void jBModificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarCActionPerformed
        int fila = jTable.getSelectedRow();
        if(fila>=0){
            jTFIDC.setText(jTable.getValueAt(fila, 0).toString());
            jTFNombreC.setText(jTable.getValueAt(fila, 1).toString());
            jTFApellido1.setText(jTable.getValueAt(fila, 2).toString());
            jTFApellido2.setText(jTable.getValueAt(fila, 3).toString());
            jTFTelefono.setText(jTable.getValueAt(fila, 4).toString());
            jTFDireccion.setText(jTable.getValueAt(fila, 5).toString());
            jTFCiudad.setText(jTable.getValueAt(fila, 6).toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila.");
        }
    }//GEN-LAST:event_jBModificarCActionPerformed

    private void jBActualizarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarCActionPerformed
        String[] cliente = new String[7];
        obtenerDatosCliente(cliente);
        String Query = "UPDATE "+"clientes"+" SET nombre='"+cliente[1]+"',apellido1='"+cliente[2]+"',apellido2='"+cliente[3]+"',telefono='"+cliente[4]+"',direccion='"+cliente[5]+"',ciudad='"+cliente[6]+"' WHERE clienteID='"+cliente[0]+"'";
        db.insertData(Query);
        cliente = null;
    }//GEN-LAST:event_jBActualizarCActionPerformed

    private void jBAnadirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnadirCActionPerformed
        String ID,nombre,ap1,ap2,tel,dir,ciu;
        ID = jTFIDC.getText();
        nombre = jTFNombreC.getText();
        ap1 = jTFApellido1.getText();
        ap2 = jTFApellido2.getText();
        tel = jTFTelefono.getText();
        dir = jTFDireccion.getText();
        ciu = jTFCiudad.getText();
        String Query = "INSERT INTO "+"clientes"+" Values("+"\""+ ID + "\", " + "\"" + nombre + "\", " + "\"" + ap1 + "\", " + "\""+ ap2 + "\", "+"\""+ tel + "\", "+"\"" + dir + "\", " + "\"" + ciu + "\")";
        db.insertData(Query);
    }//GEN-LAST:event_jBAnadirCActionPerformed

    private void jBMostrarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarClientesActionPerformed
        ResultSet res=mt.consultaTodo("clientes");
        modelo=mt.resetTableModel(modelo,jTable);
        mt.setTableHeader(res,modelo,jTable);
        mt.setTableData(res,jTable,modelo);
        mt.setComboBox(res,jComboBox1,CBModel);
    }//GEN-LAST:event_jBMostrarClientesActionPerformed

    private void jBBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarCActionPerformed
        int index=jComboBox1.getSelectedIndex();
        String Query = "SELECT * FROM clientes WHERE "+jComboBox1.getSelectedItem()+" = '"+jTFBuscarC.getText()+"'";
        ResultSet res=mt.buscarConsulta("clientes",Query);
        mt.setTableData(res, jTable, modelo);
    }//GEN-LAST:event_jBBuscarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ERPMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ERPMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ERPMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ERPMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ERPMain().setVisible(true);
            }
        });
    }
    
   public String[] obtenerDatosCliente(String[] cliente){
        cliente[0] = jTFIDC.getText();
        cliente[1] = jTFNombreC.getText();
        cliente[2] = jTFApellido1.getText();
        cliente[3] = jTFApellido2.getText();
        cliente[4] = jTFTelefono.getText();
        cliente[5] = jTFDireccion.getText();
        cliente[6] = jTFCiudad.getText();
        return cliente;
   }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarC;
    private javax.swing.JButton jBAnadirC;
    private javax.swing.JButton jBBuscarC;
    private javax.swing.JButton jBEliminarC;
    private javax.swing.JButton jBModificarC;
    private javax.swing.JButton jBMostrarClientes;
    protected javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPClientes;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFApellido1;
    private javax.swing.JTextField jTFApellido2;
    private javax.swing.JTextField jTFBuscarC;
    private javax.swing.JTextField jTFCiudad;
    private javax.swing.JTextField jTFDireccion;
    private javax.swing.JTextField jTFIDC;
    private javax.swing.JTextField jTFNombreC;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
    protected javax.swing.table.DefaultTableModel modelo;
    protected DefaultComboBoxModel CBModel;
}
