/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package erp;

import static erp.ERPMain.mt;
import java.sql.ResultSet;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author Dani
 */
public class JPProveedores extends javax.swing.JPanel {

    /**
     * Creates new form JPProveedores
     */
    public JPProveedores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPProveedores = new javax.swing.JPanel();
        jLProductos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jBMostrarProv = new javax.swing.JButton();
        jTFBuscarP = new javax.swing.JTextField();
        jBBuscarProv = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTFIDProv = new javax.swing.JTextField();
        jTFNombreProv = new javax.swing.JTextField();
        jTFDirecProv = new javax.swing.JTextField();
        jTFCiudadProv = new javax.swing.JTextField();
        jTFTelfProv = new javax.swing.JTextField();
        jTFWebProv = new javax.swing.JTextField();
        jBAnadirProv = new javax.swing.JButton();
        jBActualizarProv = new javax.swing.JButton();
        jBModificarProv = new javax.swing.JButton();
        jBEliminarProv = new javax.swing.JButton();

        jLProductos.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLProductos.setText("PROVEEDORES");

        jTable.setAutoCreateRowSorter(true);
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable);

        jLabel1.setText("Buscar por:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jBMostrarProv.setText("Mostrar todos");
        jBMostrarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBMostrarProvActionPerformed(evt);
            }
        });

        jBBuscarProv.setText("Buscar");
        jBBuscarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarProvActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("ID:");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Nombre:");

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Direccion:");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Ciudad:");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Telefono:");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Web:");

        jBAnadirProv.setText("Añadir");
        jBAnadirProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAnadirProvActionPerformed(evt);
            }
        });

        jBActualizarProv.setText("Actualizar");
        jBActualizarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTFNombreProv, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                    .addComponent(jTFDirecProv)
                    .addComponent(jTFIDProv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTFTelfProv, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(jTFWebProv)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFCiudadProv, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBActualizarProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBAnadirProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(66, 66, 66))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTFIDProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBAnadirProv)
                            .addComponent(jLabel5)
                            .addComponent(jTFCiudadProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jBActualizarProv)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFTelfProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFWebProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFNombreProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTFDirecProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jBModificarProv.setText("Modificar");
        jBModificarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBModificarProvActionPerformed(evt);
            }
        });

        jBEliminarProv.setText("Eliminar");
        jBEliminarProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarProvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPProveedoresLayout = new javax.swing.GroupLayout(jPProveedores);
        jPProveedores.setLayout(jPProveedoresLayout);
        jPProveedoresLayout.setHorizontalGroup(
            jPProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLProductos)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addGroup(jPProveedoresLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTFBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscarProv)
                        .addGap(18, 18, 18)
                        .addComponent(jBMostrarProv))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBModificarProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBEliminarProv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPProveedoresLayout.setVerticalGroup(
            jPProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLProductos)
                .addGap(18, 18, 18)
                .addGroup(jPProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBMostrarProv)
                    .addComponent(jTFBuscarP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBBuscarProv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPProveedoresLayout.createSequentialGroup()
                        .addComponent(jBModificarProv)
                        .addGap(18, 18, 18)
                        .addComponent(jBEliminarProv)))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableMouseClicked
        int fila = jTable.rowAtPoint(evt.getPoint());
        int columna = jTable.columnAtPoint(evt.getPoint());
    }//GEN-LAST:event_jTableMouseClicked

    private void jBMostrarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBMostrarProvActionPerformed
        ResultSet res=mt.consultaTodo("proveedores");
        modelo=mt.resetTableModel(modelo,jTable);
        mt.setTableHeader(res,modelo,jTable);
        mt.setTableData(res,jTable,modelo);
        mt.setComboBox(res,jComboBox1,CBModel);
    }//GEN-LAST:event_jBMostrarProvActionPerformed

    private void jBBuscarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarProvActionPerformed
        int index=jComboBox1.getSelectedIndex();
        String Query = "SELECT * FROM proveedores WHERE "+jComboBox1.getSelectedItem()+" = '"+jTFBuscarP.getText()+"'";
        ResultSet res=mt.buscarConsulta("proveedores",Query);
        mt.setTableData(res, jTable, modelo);
    }//GEN-LAST:event_jBBuscarProvActionPerformed

    private void jBAnadirProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAnadirProvActionPerformed
        String ID,nombre,ap1,ap2,tel,dir;
        ID = jTFIDProv.getText();
        nombre = jTFNombreProv.getText();
        ap1 = jTFDirecProv.getText();
        ap2 = jTFCiudadProv.getText();
        tel = jTFTelfProv.getText();
        dir = jTFWebProv.getText();
        String Query = "INSERT INTO "+"proveedores"+" Values("+"\""+ ID + "\", " + "\"" + nombre + "\", " + "\"" + ap1 + "\", " + "\""+ ap2 + "\", "+"\""+ tel + "\", "+"\"" + dir + "\")";
        ERPMain.db.insertData(Query);
    }//GEN-LAST:event_jBAnadirProvActionPerformed

    private void jBActualizarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarProvActionPerformed
        String[] proveedor = new String[6];
        obtenerDatosProveedores(proveedor);
        String Query = "UPDATE "+"proveedores"+" SET nombre='"+proveedor[1]+"',direccion='"+proveedor[2]+"',ciudad='"+proveedor[3]+"',telefono='"+proveedor[4]+"',web='"+proveedor[5]+"' WHERE proveedorID='"+proveedor[0]+"'";
        ERPMain.db.insertData(Query);
        proveedor = null;
    }//GEN-LAST:event_jBActualizarProvActionPerformed

    private void jBModificarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBModificarProvActionPerformed
        int fila = jTable.getSelectedRow();
        if(fila>=0){
            jTFIDProv.setText(jTable.getValueAt(fila, 0).toString());
            jTFNombreProv.setText(jTable.getValueAt(fila, 1).toString());
            jTFDirecProv.setText(jTable.getValueAt(fila, 2).toString());
            jTFCiudadProv.setText(jTable.getValueAt(fila, 3).toString());
            jTFTelfProv.setText(jTable.getValueAt(fila, 4).toString());
            jTFWebProv.setText(jTable.getValueAt(fila, 5).toString());
        }
        else{
            JOptionPane.showMessageDialog(null, "Seleccione una fila.");
        }
    }//GEN-LAST:event_jBModificarProvActionPerformed

    private void jBEliminarProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarProvActionPerformed
        int fila = jTable.getSelectedRow();
        if(fila>=0){
            int res=JOptionPane.showConfirmDialog(this, "¿Desea borrar el proveedor seleccionado?", "Eliminar", JOptionPane.OK_CANCEL_OPTION);
            if(res==0){
                String Query ="DELETE FROM proveedores WHERE proveedorID = \""+jTable.getValueAt(fila, 0).toString()+"\"";
                ERPMain.db.deleteRecord(Query);
            }
        }
        else{JOptionPane.showMessageDialog(null, "Seleccione una fila.");}
    }//GEN-LAST:event_jBEliminarProvActionPerformed
    
     public String[] obtenerDatosProveedores(String[] proveedor){
        proveedor[0] = jTFIDProv.getText();
        proveedor[1] = jTFNombreProv.getText();
        proveedor[2] = jTFDirecProv.getText();
        proveedor[3] = jTFCiudadProv.getText();
        proveedor[4] = jTFTelfProv.getText();
        proveedor[5] = jTFWebProv.getText();
        return proveedor;
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarProv;
    private javax.swing.JButton jBAnadirProv;
    private javax.swing.JButton jBBuscarProv;
    private javax.swing.JButton jBEliminarProv;
    private javax.swing.JButton jBModificarProv;
    private javax.swing.JButton jBMostrarProv;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLProductos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPProveedores;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTFBuscarP;
    private javax.swing.JTextField jTFCiudadProv;
    private javax.swing.JTextField jTFDirecProv;
    private javax.swing.JTextField jTFIDProv;
    private javax.swing.JTextField jTFNombreProv;
    private javax.swing.JTextField jTFTelfProv;
    private javax.swing.JTextField jTFWebProv;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel modelo;
    private DefaultComboBoxModel CBModel;
}
